### PR TITLE
fix: simplify AckSetTrackerImpl and make acks after shutdown not cause a permanent error

### LINKED ISSUE #870: Race condition on partition assignment causing the Subscriber to fail
During partition reassignment, there seems to be some race-condition when messages are `ack`ed as `SinglePartitionSubscriber` are closed during partition re-assignment. When this happen, it causes the `AssigningSubscriber` to fail.

#### Environment details

2. OS type and version: gcr.io/distroless/java:8
3. Java version: gcr.io/distroless/java:8
4. pubsublite version(s): 1.0.5

#### Steps to reproduce

I was not able to reproduce the issue in a systematic way, but for one of our subscription we saw this issue ~20 times in 4 hours. During this time there was about ~450 partition assignment.

#### Stack trace
```
com.google.api.gax.rpc.ApiException: Committed after the stream shut down.
	at com.google.cloud.pubsublite.internal.CheckedApiException.<init>(CheckedApiException.java:51)
	at com.google.cloud.pubsublite.internal.CheckedApiException.<init>(CheckedApiException.java:59)
	at com.google.cloud.pubsublite.internal.CheckedApiPreconditions.checkState(CheckedApiPreconditions.java:38)
	at com.google.cloud.pubsublite.internal.wire.CommitterImpl.commitOffset(CommitterImpl.java:137)
	at com.google.cloud.pubsublite.internal.wire.ApiExceptionCommitter.commitOffset(ApiExceptionCommitter.java:37)
	at com.google.cloud.pubsublite.cloudpubsub.internal.AckSetTrackerImpl.onAck(AckSetTrackerImpl.java:138)
	at com.google.cloud.pubsublite.cloudpubsub.internal.AckSetTrackerImpl.access$100(AckSetTrackerImpl.java:39)
	at com.google.cloud.pubsublite.cloudpubsub.internal.AckSetTrackerImpl$Receipt.onAck(AckSetTrackerImpl.java:76)
	at com.google.cloud.pubsublite.cloudpubsub.internal.SinglePartitionSubscriber$1.ack(SinglePartitionSubscriber.java:92)
	at com.hopper.common.pubsub.MessageProcessor$$anon$1.ack(MessageProcessor.scala:56)
        ...
```

#### Any additional information below

The log before this error is systematically something like `Subscribed to partitions: [Partition{value=16}, Partition{value=17}]` from `com.google.cloud.pubsublite.internal.wire.AssignerImpl`.

### PR DESCRIPTION
**Pull request by dpcollins-google**
Fixes #870 ☕️

### CODE REVIEW

File: google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java [hunk 1]
```diff
@@ -24,120 +24,117 @@
...
-import java.util.List;
 import java.util.Optional;
 import java.util.PriorityQueue;
+import java.util.concurrent.atomic.AtomicBoolean;
+
+public class AckSetTrackerImpl extends ProxyService implements AckSetTracker {
+  private static final GoogleLogger LOGGER = GoogleLogger.forEnclosingClass();
 
-public class AckSetTrackerImpl extends TrivialProxyService implements AckSetTracker {
   // Receipt represents an unacked message. It can be cleared, which will cause the ack to be
```
Comment (manuelmenzella-google) [inline google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java:41]: Nit; It can no longer be "cleared," you just increase the generation version.

**Review by manuelmenzella-google — APPROVED** [review]

File: google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java (hunk 1 above)
Comment (dpcollins-google) [reply google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java]: Done.
